In [1]:
from mpdist import mpdist
import numpy as np

In [2]:
from aeon.datasets import load_italy_power_demand
X, y = load_italy_power_demand()
from aeon.distances import euclidean_distance, dtw_distance
import time

In [3]:
X

array([[[-0.71051757, -1.1833204 , -1.3724416 , ...,  0.58181015,
          0.1720477 , -0.26923494]],

       [[-0.99300935, -1.4267865 , -1.5798843 , ...,  0.69106647,
         -0.04890624, -0.38061813]],

       [[ 1.3190669 ,  0.56977448,  0.19512825, ...,  2.3493441 ,
          2.2556825 ,  1.6000516 ]],

       ...,

       [[-1.2627064 , -1.4497741 , -1.5199244 , ...,  0.81842084,
          0.28060142, -0.14030072]],

       [[ 0.71432123,  0.62902914,  0.11727662, ...,  2.420163  ,
          2.1642867 ,  1.9084104 ]],

       [[-0.58214415, -1.1312408 , -1.4973052 , ...,  0.72958677,
          0.21099547, -0.00254212]]])

In [4]:
X.shape

(1096, 1, 24)

In [5]:
mp_distance = mpdist(X[0], X[1], m = 6)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
NameError: name 'len1' is not defined

In [13]:
mp_distance

0.39838992655731575

In [15]:
euclidean = euclidean_distance(X[0],X[1])
euclidean

2.2105998447490136

In [16]:
dtw = dtw_distance(X[0], X[1])
dtw

2.2562779371935555

In [17]:


# DO NOT REPORT THIS... COMPILATION TIME IS INCLUDED IN THE EXECUTION TIME!
start = time.perf_counter()
mp_distance = mpdist(X[3], X[8], m = 8)
end = time.perf_counter()
print("Elapsed (with compilation) = {}s".format((end - start)))

# NOW THE FUNCTION IS COMPILED, RE-TIME IT EXECUTING FROM CACHE
start = time.perf_counter()
mp_distance = mpdist(X[3], X[8], m = 8)
end = time.perf_counter()
print("Elapsed (after compilation) = {}s".format((end - start)))

Elapsed (with compilation) = 0.008843800000249757s
Elapsed (after compilation) = 0.009764800000084506s


In [8]:
# DO NOT REPORT THIS... COMPILATION TIME IS INCLUDED IN THE EXECUTION TIME!
start = time.perf_counter()
dtw = dtw_distance(X[0], X[1])
end = time.perf_counter()
print("Elapsed (with compilation) = {}s".format((end - start)))

# NOW THE FUNCTION IS COMPILED, RE-TIME IT EXECUTING FROM CACHE
start = time.perf_counter()
dtw = dtw_distance(X[0], X[1])
end = time.perf_counter()
print("Elapsed (after compilation) = {}s".format((end - start)))

Elapsed (with compilation) = 0.7887432999996236s
Elapsed (after compilation) = 0.0003375000005689799s


In [9]:
# DO NOT REPORT THIS... COMPILATION TIME IS INCLUDED IN THE EXECUTION TIME!
start = time.perf_counter()
mp_distance = mpdist(X[3], X[8], m = 8)
end = time.perf_counter()
print("Elapsed (with compilation) = {}s".format((end - start)))

# NOW THE FUNCTION IS COMPILED, RE-TIME IT EXECUTING FROM CACHE
start = time.perf_counter()
mp_distance = mpdist(X[3], X[8], m = 8)
end = time.perf_counter()
print("Elapsed (after compilation) = {}s".format((end - start)))

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'squeeze' of type array(float64, 2d, C)

File "mpdist.py", line 79:
def mpdist(
    <source elided>
        raise ValueError("y must be a 1D array or shape (1,n)")
    x = x.squeeze()
    ^

During: typing of get attribute at D:\Python\Project\Aeon\Probabilistic-Programming\mpdist.py (79)

File "mpdist.py", line 79:
def mpdist(
    <source elided>
        raise ValueError("y must be a 1D array or shape (1,n)")
    x = x.squeeze()
    ^


## MPDist

import numpy as np
from numba import njit


@njit(cache=True, fastmath=True)
def mpdist(
    x: np.ndarray,
    y: np.ndarray,
    m: int = 0
) -> float:
    r"""Compute the Matrix Profile distance between two time series.

    Parameters
    ----------
    x : np.ndarray
        First time series, either univariate, shape ``(n_timepoints,)``, or
        multivariate, shape ``(n_channels, n_timepoints)``.
    y : np.ndarray
        Second time series, either univariate, shape ``(n_timepoints,)``, or
        multivariate, shape ``(n_channels, n_timepoints)``.
    m : int
        Length of the subsequence.

    Returns
    -------
    float
        Matrix Profile distance between x and y, minimum value 0.

    Raises
    ------
    ValueError
        If x and y are not 1D or 2D arrays.

    References
    ----------
    .. [1] Ratanamahatana C and Keogh E.: Three myths about dynamic time warping data
    mining, Proceedings of 5th SIAM International Conference on Data Mining, 2005.

    .. [2] Sakoe H. and Chiba S.: Dynamic programming algorithm optimization for
    spoken word recognition. IEEE Transactions on Acoustics, Speech, and Signal
    Processing 26(1):43–49, 1978.

    Examples
    --------
    >>> import numpy as np
    >>> from aeon.distances import mpdist
    >>> x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    >>> y = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
    >>> mpdist(x, y) # 1D series
    768.0
    >>> x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [0, 1, 0, 2, 0]])
    >>> y = np.array([[11, 12, 13, 14],[7, 8, 9, 20],[1, 3, 4, 5]] )
    >>> mpdist(x, y) # 2D series wi
    if (x.ndim == 2 and x.shape[0] > 1) or (y.ndim == 2 and y.shape[0] > 1):
        raise ValueError("xand y must be a 1D array or shape (1,n)")

    return _mpdistance(x,y,m)

def _mpdist(x: np.ndarray, y: np.ndarray, m: int) -> float:
    if m == 0:
        if len(x)>len(y):
            m = int(len(x)/4)th 3 channels, unequal length
    564.0
    """


In [23]:
x = np.array([1,3,5,13,15])
y = np.array([2,4,8,12,18])
print(y.ndim)

1


In [24]:
x

array([ 1,  3,  5, 13, 15])

In [30]:
x = x.reshape((1,5))
x.shape

(1, 5)

In [31]:
x = x.squeeze()
x

array([ 1,  3,  5, 13, 15])

In [32]:
x.shape

(5,)